### ISSUE TITLE
no data received

### ISSUE THREAD

**Issue by onli** [rockets/rockets#3]
That might be an error on my side, but:

Since ~two days ago, my rocket-demo (https://github.com/onli/radellite) stopped working. Right from the start, it just does not receive any notifications from rocket. Tested that on two different machines, with and without filters, bumped up the rocket-client demo – nothing. Is that caused by #2, is that blocking the server completely currently?

**Comment by rtheunissen** [comment]
Unfortunately yes, this is caused by #2. I try my best to restart the server as soon as I realise it has stopped receiving data. This often happens when I'm sleeping and it's difficult to detect when it happens. I can't promise perfect uptime until #2 is fixed. I'm sorry :/

**Comment by onli** [comment]
Hey, not a problem, thanks for trying to keep it up. Good luck with catching the bug (I searched a bit, but am not a node developer and out of my league here).

**Comment by onli** [comment]
Hi. Just as a note, It looks like it got stuck again.

**Comment by rtheunissen** [comment]
I'm tempted to rewrite this in Go or something...

**Comment by onli** [comment]
You can probably workaround it by detecting the memory leak/the inactivity (that is still what is happening?) with an external program and then automatically restarting rocket. Read that quite some node projects have to resort to stuff like this.

But if you rewrite and then submit an article to HN, you will get lots of upvotes ;) 

Get in contact if I can help somehow. Still find rockets really useful.

**Comment by ddormer** [comment]
A rewrite with node removed is probably a good idea. :)

**Comment by onli** [comment]
I saw that you said that you are in a rewrite, and that you restarted the process. Should rocket currently work? I still get no data, but since I got no data even after a rocket restart I'm thinking that maybe something on my side is broken. Do you know the current state?

**Comment by rtheunissen** [comment]
Hi all. I've upgrading the server and restarted the process. I have no guarantees at this point for how long it'll keep running for. I'll check it every morning. I don't like the idea of a monitoring solution to restart the process - it shouldn't be crashing in the first place.

**Comment by rtheunissen** [comment]
If anyone would be interested in the server logs to try debug this, let me know.
