### ISSUE TITLE
Rockets is down again?

### ISSUE THREAD

**Issue by Warix3** [rockets/rockets#8]
I'm getting the  Error: connect ECONNREFUSED 

{ Error: connect ECONNREFUSED 45.33.55.106:3210
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '45.33.55.106',
  port: 3210 }

when i run the demo project.

**Comment by rtheunissen** [comment]
Rockets is currently not running on a server anywhere. I still have to get around to fixing a core bug that caused it to freeze from time to time. Sorry about that. You're welcome to try run your own instance though.

**Comment by sometimescool22** [comment]
Hey, has this issue been fixed? I'm still getting connection refused.
